server:
  port: 8080
spring:
  mvc:
    view:
      prefix: src/main/resources
      suffix: .html
  datasource:
    url: jdbc:postgresql://localhost:5432/apps4Society
    username: postgres
    password: 6036236
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hiberEnate:
        temp:
          use_jdbc_metadata_defaults: false
  


          
