server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://apps4society-2018.database.windows.net:1433;database=apps4Society;user=SuperSecreto;password=SuperSecreto;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hiberEnate:
        temp:
          use_jdbc_metadata_defaults: false
